'use strict';

const hana = require('@sap/hana-client');

/**
 * HANA-backed implementation of the item repository.
 *
 * Stores an arbitrary JSON payload as an NCLOB. All statements are
 * parameterized to avoid SQL injection. The table name is validated as a
 * plain identifier because it cannot be parameterized.
 */
function createHanaRepository(credentials, tableName = 'ITEMS') {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(tableName)) {
    throw new Error(`Invalid table name: ${tableName}`);
  }
  const schema = credentials.schema;
  if (schema && !/^[A-Za-z_][A-Za-z0-9_]*$/.test(schema)) {
    throw new Error(`Invalid schema name: ${schema}`);
  }

  // Fully-qualified, quoted table reference. When a schema is provided (HDI
  // container), objects live there; otherwise the user's default schema.
  const table = schema ? `"${schema}"."${tableName}"` : `"${tableName}"`;

  const conn = hana.createConnection();
  let ready = false;

  function connect() {
    return new Promise((resolve, reject) => {
      const connectParams = {
        serverNode: `${credentials.host}:${credentials.port}`,
        uid: credentials.user,
        pwd: credentials.password,
        encrypt: credentials.encrypt ? 'true' : 'false',
        sslValidateCertificate: credentials.sslValidateCertificate ? 'true' : 'false',
      };
      if (schema) {
        connectParams.currentSchema = schema;
      }
      conn.connect(connectParams, (err) => (err ? reject(err) : resolve()));
    });
  }

  function exec(sql, params = []) {
    return new Promise((resolve, reject) => {
      conn.prepare(sql, (prepErr, statement) => {
        if (prepErr) return reject(prepErr);
        statement.exec(params, (execErr, result) => {
          statement.drop(() => {});
          if (execErr) return reject(execErr);
          resolve(result);
        });
      });
    });
  }

  return {
    isReady() {
      return ready;
    },

    async init() {
      await connect();
      // CREATE TABLE IF NOT EXISTS is not supported by HANA, so we
      // attempt creation and ignore the "already exists" error (259).
      const createSql =
        `CREATE COLUMN TABLE ${table} (` +
        `"ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ` +
        `"PAYLOAD" NCLOB, ` +
        `"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`;
      try {
        await exec(createSql);
      } catch (err) {
        // 288 = table already exists, 259 = invalid table name (exists)
        if (err.code !== 288 && err.code !== 259) {
          throw err;
        }
      }
      ready = true;
    },

    async insert(payload) {
      const text = JSON.stringify(payload);
      const insertSql = `INSERT INTO ${table} ("PAYLOAD") VALUES (?)`;
      await exec(insertSql, [text]);
      const rows = await exec(
        `SELECT "ID", "PAYLOAD", "CREATED_AT" FROM ${table} ` +
          `WHERE "ID" = (SELECT MAX("ID") FROM ${table})`
      );
      const row = rows[0];
      return {
        id: Number(row.ID),
        payload: JSON.parse(row.PAYLOAD),
        created_at: new Date(row.CREATED_AT).toISOString(),
      };
    },

    async list() {
      const rows = await exec(
        `SELECT "ID", "PAYLOAD", "CREATED_AT" FROM ${table} ORDER BY "ID" DESC`
      );
      return rows.map((row) => ({
        id: Number(row.ID),
        payload: JSON.parse(row.PAYLOAD),
        created_at: new Date(row.CREATED_AT).toISOString(),
      }));
    },

    async close() {
      return new Promise((resolve) => conn.disconnect(() => resolve()));
    },
  };
}

module.exports = { createHanaRepository };
